export interface Employer {
  id: string;
  name: string;
  tagline: string;
  industry: string;
  rating: number;
  reviewCount: number;
  location: string;
  costRange: string;
  openJobs: number;
  logoColor: string;
  logoText: string;
  isSaved?: boolean;
  description: string;
  website: string;
  teamSize: string;
}

export const DEFAULT_EMPLOYERS: Employer[] = [
  {
    id: 'emp-mailchimp-1',
    name: 'Mailchimp',
    tagline: 'Unify your email campaigns and automated advertising flows.',
    industry: 'Web & App Design',
    rating: 4.9,
    reviewCount: 142,
    location: 'London, UK',
    costRange: '$60 - $110 / hr',
    openJobs: 29,
    logoColor: 'monkey-face',
    logoText: 'MC',
    isSaved: true,
    description:
      'Mailchimp is an all-in-one marketing platform that helps businesses grow. We integrate your customer data, design templates, smart email automation campaigns, and performant feedback loops in one workspace.',
    website: 'https://mailchimp.com',
    teamSize: '500+ employees',
  },
  {
    id: 'emp-mailchimp-2',
    name: 'Mailchimp',
    tagline: 'Premium visual assets, web dashboard designs, and performance tools.',
    industry: 'Frontend Development',
    rating: 4.5,
    reviewCount: 89,
    location: 'New York, USA',
    costRange: '$75 - $130 / hr',
    openJobs: 29,
    logoColor: 'wave-s',
    logoText: 'MC',
    isSaved: false,
    description:
      'Leading digital system architectures designed for hyper-growth brands. Our focus lies inside client-centric user experiences, fast frontend load bounds, and beautifully configured layouts.',
    website: 'https://mailchimp.com',
    teamSize: '100-250 employees',
  },
  {
    id: 'emp-mailchimp-3',
    name: 'Mailchimp',
    tagline: 'Innovative copy storytelling, editorial assets, and content systems.',
    industry: 'Copywriting & Content',
    rating: 3.8,
    reviewCount: 41,
    location: 'Tokyo, Japan',
    costRange: '$50 - $90 / hr',
    openJobs: 29,
    logoColor: 'cursive-in',
    logoText: 'MC',
    isSaved: false,
    description:
      'Breathtaking global copywriting campaigns aimed at conversions. We translate product objectives and value propositions into readable, inspiring prose.',
    website: 'https://mailchimp.com',
    teamSize: '15-50 employees',
  },
  {
    id: 'emp-mailchimp-4',
    name: 'Mailchimp',
    tagline: 'High scalability database pipelines, secure microservices, and server systems.',
    industry: 'Backend Engineering',
    rating: 4.2,
    reviewCount: 76,
    location: 'Berlin, Germany',
    costRange: '$80 - $140 / hr',
    openJobs: 29,
    logoColor: 'linked-loops',
    logoText: 'MC',
    isSaved: false,
    description:
      'Secure, performant and resilient cloud infrastructures. We program customized API endpoints, event-driven compute loops, and secure ledger databases.',
    website: 'https://mailchimp.com',
    teamSize: '50-100 employees',
  },
  {
    id: 'emp-mailchimp-5',
    name: 'Mailchimp',
    tagline: 'Stunning Figma prototypes and fluid digital design systems.',
    industry: 'UI/UX Prototyping',
    rating: 4.7,
    reviewCount: 95,
    location: 'Paris, France',
    costRange: '$65 - $120 / hr',
    openJobs: 29,
    logoColor: 'retro-grid',
    logoText: 'MC',
    isSaved: false,
    description:
      'Editorial UI/UX configurations focused on tactile user interactions. We map precise customer navigation paths, layout proportions, and custom transition systems.',
    website: 'https://mailchimp.com',
    teamSize: '5-15 employees',
  },
  {
    id: 'emp-mailchimp-6',
    name: 'Mailchimp',
    tagline: 'Growth marketing solutions, conversion optimization, and SEO campaigns.',
    industry: 'Digital Marketing',
    rating: 3.5,
    reviewCount: 28,
    location: 'Sydney, Australia',
    costRange: '$45 - $85 / hr',
    openJobs: 29,
    logoColor: 'serif-m',
    logoText: 'MC',
    isSaved: true,
    description:
      'Amplify your product conversions. We audit analytics funnels, build retargeting assets, and scale search engine visibility matrices.',
    website: 'https://mailchimp.com',
    teamSize: '15-50 employees',
  },
  {
    id: 'emp-mailchimp-7',
    name: 'Mailchimp',
    tagline: 'Custom ecommerce engineering, Shopify flows, and modern checkout systems.',
    industry: 'Frontend Development',
    rating: 4.6,
    reviewCount: 112,
    location: 'Toronto, Canada',
    costRange: '$85 - $160 / hr',
    openJobs: 29,
    logoColor: 'cursive-u',
    logoText: 'MC',
    isSaved: false,
    description:
      'Outstanding retail engineering solutions connecting your core inventories to beautiful high-performance checkout funnels.',
    website: 'https://mailchimp.com',
    teamSize: '50-100 employees',
  },
  {
    id: 'emp-mailchimp-8',
    name: 'Mailchimp',
    tagline: 'Fullstack product engineering and mobile application buildouts.',
    industry: 'Web & App Design',
    rating: 4.3,
    reviewCount: 64,
    location: 'Mumbai, India',
    costRange: '$40 - $75 / hr',
    openJobs: 29,
    logoColor: 'figma-icon',
    logoText: 'MC',
    isSaved: false,
    description:
      'A fast, fully responsive design and deployment lifecycle provider. We engineering premium systems utilizing React, Node, and Tailwind CSS styles.',
    website: 'https://mailchimp.com',
    teamSize: '100-250 employees',
  },
  {
    id: 'emp-slack',
    name: 'Slack Technologies',
    tagline: 'Where work happens: real-time unified communication systems.',
    industry: 'Web & App Design',
    rating: 4.9,
    reviewCount: 420,
    location: 'San Francisco, USA',
    costRange: '$90 - $185 / hr',
    openJobs: 14,
    logoColor: 'slack-icon',
    logoText: 'SL',
    isSaved: false,
    description:
      'Slack makes workspace communications pleasant, instant, and fully integrated with your favorite automated deployment APIs.',
    website: 'https://slack.com',
    teamSize: '500+ employees',
  },
  {
    id: 'emp-airbnb',
    name: 'Airbnb Inc.',
    tagline: 'Belong anywhere: global community rental platform layouts.',
    industry: 'UI/UX Prototyping',
    rating: 4.8,
    reviewCount: 310,
    location: 'San Francisco, USA',
    costRange: '$85 - $170 / hr',
    openJobs: 22,
    logoColor: 'airbnb-icon',
    logoText: 'AB',
    isSaved: true,
    description:
      'Delivering gorgeous real-world booking experiences and tactile travel designs across mobile apps and web platforms.',
    website: 'https://airbnb.com',
    teamSize: '500+ employees',
  },
  {
    id: 'emp-stripe',
    name: 'Stripe',
    tagline: 'Financial developer APIs for global internet businesses.',
    industry: 'Backend Engineering',
    rating: 4.95,
    reviewCount: 512,
    location: 'Dublin, Ireland',
    costRange: '$100 - $220 / hr',
    openJobs: 35,
    logoColor: 'stripe-icon',
    logoText: 'ST',
    isSaved: false,
    description:
      'Stripe is a suite of APIs powering online payments, fraud mitigation tools, billing subscriptions, and banking services.',
    website: 'https://stripe.com',
    teamSize: '500+ employees',
  },
  {
    id: 'emp-shopify',
    name: 'Shopify',
    tagline: 'Powering independent retail systems across all digital channels.',
    industry: 'Frontend Development',
    rating: 4.75,
    reviewCount: 260,
    location: 'Ottawa, Canada',
    costRange: '$80 - $150 / hr',
    openJobs: 18,
    logoColor: 'shopify-icon',
    logoText: 'SP',
    isSaved: false,
    description:
      'Shopify establishes modern commerce infrastructure so millions of developers and retailers can scale storefronts without friction.',
    website: 'https://shopify.com',
    teamSize: '500+ employees',
  },
  {
    id: 'emp-zoom',
    name: 'Zoom Video',
    tagline: 'Crystal clear virtual conferencing, meetings, and stream engines.',
    industry: 'Backend Engineering',
    rating: 4.4,
    reviewCount: 195,
    location: 'San Jose, USA',
    costRange: '$70 - $135 / hr',
    openJobs: 8,
    logoColor: 'zoom-icon',
    logoText: 'ZM',
    isSaved: false,
    description:
      'Providing high-fidelity, ultra-low latency video streaming services, collaboration chats, and digital meeting spaces.',
    website: 'https://zoom.us',
    teamSize: '500+ employees',
  },
  {
    id: 'emp-spotify',
    name: 'Spotify',
    tagline: 'Streaming loop networks connecting millions of vocal artists.',
    industry: 'Digital Marketing',
    rating: 4.85,
    reviewCount: 380,
    location: 'Stockholm, Sweden',
    costRange: '$95 - $190 / hr',
    openJobs: 16,
    logoColor: 'spotify-icon',
    logoText: 'SF',
    isSaved: true,
    description:
      'An offline-first streaming service providing millions of tracks, curated radio playlists, podcasts, and video casts.',
    website: 'https://spotify.com',
    teamSize: '500+ employees',
  },
  {
    id: 'emp-google',
    name: 'Google LLC',
    tagline: "Organizing the internet's catalog of information securely.",
    industry: 'Frontend Development',
    rating: 4.9,
    reviewCount: 940,
    location: 'Mountain View, USA',
    costRange: '$120 - $250 / hr',
    openJobs: 42,
    logoColor: 'brand-google',
    logoText: 'GG',
    isSaved: false,
    description:
      'Building the digital entryways of the future. Specializing in semantic query crawlers, chromium interfaces, and cloud architectures.',
    website: 'https://google.com',
    teamSize: '500+ employees',
  },
  {
    id: 'emp-notion',
    name: 'Notion Labs',
    tagline: 'The connected workspace for docs, wikis, and task structures.',
    industry: 'UI/UX Prototyping',
    rating: 4.8,
    reviewCount: 175,
    location: 'Tokyo, Japan',
    costRange: '$75 - $130 / hr',
    openJobs: 11,
    logoColor: 'notion-icon',
    logoText: 'NT',
    isSaved: false,
    description:
      'Notion brings databases, customized text layouts, lists, and docs together seamlessly for optimal team coordination.',
    website: 'https://notion.so',
    teamSize: '100-250 employees',
  },
];

export const EMPLOYER_INDUSTRIES = [
  'Category',
  'Web & App Design',
  'Frontend Development',
  'Backend Engineering',
  'UI/UX Prototyping',
  'Digital Marketing',
  'Copywriting & Content',
] as const;

export const EMPLOYER_TEAM_SIZES = [
  'No of Employees',
  '5-15 employees',
  '15-50 employees',
  '50-100 employees',
  '100-250 employees',
  '500+ employees',
] as const;

export const EMPLOYER_SORT_OPTIONS = ['Best Seller', 'Review Count', 'Open Jobs'] as const;

export const EMPLOYER_LOGO_KEYS = [
  'monkey-face',
  'wave-s',
  'cursive-in',
  'linked-loops',
  'retro-grid',
  'serif-m',
  'cursive-u',
  'figma-icon',
] as const;

export const ITEMS_PER_PAGE = 8;
